version: '3.8'

services:
  web:
    build:
      context: ./
      target: dev
    volumes:
      - ./:/app
 #     - /usr/src/app/node_modules
    command: npm run start:dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
